# -*- coding: UTF-8 -*-
__author__ = 'mohammed'

ara = {
    'product':'المنتج',
    'products':'المنتجات',
    'customer':'عميل',
    'customers':'عملاء',
    'bill':'فاتورة',
    'bills':'فواتير',
    'category':'تصنيف',
    'categories':'تصنيفات',
    'store':'مخزن',
    'stores':'مخازن',
    'analys':'تحليل',
    'admincp':'لوحة التحكم',
    'all':'كُل',
    'login':'دخول',
    'logout':'خروج',
    'edit':'تعديل',
    'new':'جديد',
    'delete':'حذف',
    'search':'بحث',
    'username':'إسم المستخدم',
    'password':'كلمة المرور',
    'first_name':'الأسم الأول',
    'last_name':'الأسم الأخير',
    'email':'البريد',
    'perm':'التصاريح',
    'number':'عدد',
    'address':'عنوان',
    'disc':'الوصف',
    'add':'إضافة',
    'price':'السعر',
    'sell_price':'سعر البيع',
    'name':'الإسم',
},
eng = {
    'product':'Product',
    'products':'Products',
    'customer':'Customer',
    'customers':'Customers',
    'bill':'Bill',
    'bills':'Bills',
    'category':'Category',
    'categories':'Categories',
    'store':'Store',
    'stores':'Stores',
    'analys':'Analys',
    'admincp':'Admincp',
    'all':'All',
    'login':'Login',
    'logout':'Logout',
    'edit':'Edit',
    'new':'New',
    'delete':'Delete',
    'search':'Search',
    'username':'Username',
    'password':'Password',
    'first_name':'First Name',
    'last_name':'Last Name',
    'email':'Email',
    'perm':'Perm',
    'number':'Number',
    'address':'Address',
    'disc':'Disc',
    'add':'Add',
    'price':'Price',
    'sell_price':'Sell Price',
    'name':'Name',
}